/**
 * generated by Xtext
 */
package org.xtext.example.generator;

import javax.inject.Inject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.xtext.example.generator.PrettyPrinterGenerator;
import org.xtext.example.generator.UglyPrinterGenerator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class WhileCppGenerator implements IGenerator {
  @Inject
  private PrettyPrinterGenerator PrettyGen;
  
  @Inject
  private UglyPrinterGenerator UglyGen;
  
  @Override
  public void doGenerate(final Resource input, final IFileSystemAccess fsa) {
    this.PrettyGen.doGenerate(input, fsa);
    this.UglyGen.doGenerate(input, fsa);
  }
}
