/*
 * generated by Xtext
 */
package org.xtext.example.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.services.WhileCppGrammarAccess;
import org.xtext.example.whileCpp.Command;
import org.xtext.example.whileCpp.CommandForEach;
import org.xtext.example.whileCpp.CommandIf;
import org.xtext.example.whileCpp.CommandWhile;
import org.xtext.example.whileCpp.Commands;
import org.xtext.example.whileCpp.Cons;
import org.xtext.example.whileCpp.Definition;
import org.xtext.example.whileCpp.Expr;
import org.xtext.example.whileCpp.ExprAnd;
import org.xtext.example.whileCpp.ExprEq;
import org.xtext.example.whileCpp.ExprNot;
import org.xtext.example.whileCpp.ExprOr;
import org.xtext.example.whileCpp.ExprSimple;
import org.xtext.example.whileCpp.Exprs;
import org.xtext.example.whileCpp.Function;
import org.xtext.example.whileCpp.Input;
import org.xtext.example.whileCpp.Output;
import org.xtext.example.whileCpp.Program;
import org.xtext.example.whileCpp.Vars;
import org.xtext.example.whileCpp.WhileCppPackage;

@SuppressWarnings("all")
public class WhileCppSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private WhileCppGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == WhileCppPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case WhileCppPackage.COMMAND:
				sequence_Command(context, (Command) semanticObject); 
				return; 
			case WhileCppPackage.COMMAND_FOR_EACH:
				sequence_CommandForEach(context, (CommandForEach) semanticObject); 
				return; 
			case WhileCppPackage.COMMAND_IF:
				sequence_CommandIf(context, (CommandIf) semanticObject); 
				return; 
			case WhileCppPackage.COMMAND_WHILE:
				sequence_CommandWhile(context, (CommandWhile) semanticObject); 
				return; 
			case WhileCppPackage.COMMANDS:
				sequence_Commands(context, (Commands) semanticObject); 
				return; 
			case WhileCppPackage.CONS:
				sequence_Cons(context, (Cons) semanticObject); 
				return; 
			case WhileCppPackage.DEFINITION:
				sequence_Definition(context, (Definition) semanticObject); 
				return; 
			case WhileCppPackage.EXPR:
				sequence_Expr(context, (Expr) semanticObject); 
				return; 
			case WhileCppPackage.EXPR_AND:
				sequence_ExprAnd(context, (ExprAnd) semanticObject); 
				return; 
			case WhileCppPackage.EXPR_EQ:
				sequence_ExprEq(context, (ExprEq) semanticObject); 
				return; 
			case WhileCppPackage.EXPR_NOT:
				sequence_ExprNot(context, (ExprNot) semanticObject); 
				return; 
			case WhileCppPackage.EXPR_OR:
				sequence_ExprOr(context, (ExprOr) semanticObject); 
				return; 
			case WhileCppPackage.EXPR_SIMPLE:
				sequence_ExprSimple(context, (ExprSimple) semanticObject); 
				return; 
			case WhileCppPackage.EXPRS:
				sequence_Exprs(context, (Exprs) semanticObject); 
				return; 
			case WhileCppPackage.FUNCTION:
				sequence_Function(context, (Function) semanticObject); 
				return; 
			case WhileCppPackage.INPUT:
				sequence_Input(context, (Input) semanticObject); 
				return; 
			case WhileCppPackage.OUTPUT:
				sequence_Output(context, (Output) semanticObject); 
				return; 
			case WhileCppPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case WhileCppPackage.VARS:
				sequence_Vars(context, (Vars) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (elem=Expr ensemb=Expr cmds=Commands)
	 */
	protected void sequence_CommandForEach(EObject context, CommandForEach semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.COMMAND_FOR_EACH__ELEM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.COMMAND_FOR_EACH__ELEM));
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.COMMAND_FOR_EACH__ENSEMB) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.COMMAND_FOR_EACH__ENSEMB));
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.COMMAND_FOR_EACH__CMDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.COMMAND_FOR_EACH__CMDS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getCommandForEachAccess().getElemExprParserRuleCall_1_0(), semanticObject.getElem());
		feeder.accept(grammarAccess.getCommandForEachAccess().getEnsembExprParserRuleCall_3_0(), semanticObject.getEnsemb());
		feeder.accept(grammarAccess.getCommandForEachAccess().getCmdsCommandsParserRuleCall_5_0(), semanticObject.getCmds());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (cond=Expr cmdsThen=Commands cmdsElse=Commands?)
	 */
	protected void sequence_CommandIf(EObject context, CommandIf semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (w='while'? expr=Expr cmds=Commands)
	 */
	protected void sequence_CommandWhile(EObject context, CommandWhile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (nop='nop' | (vars=Vars exprs=Exprs) | cmdWhile=CommandWhile | cmdIf=CommandIf | cmdForEach=CommandForEach)
	 */
	protected void sequence_Command(EObject context, Command semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (commande+=Command* commande+=Command)
	 */
	protected void sequence_Commands(EObject context, Commands semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (exprCons='cons' exprConsAttList+=Expr+)
	 */
	protected void sequence_Cons(EObject context, Cons semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (inputs=Input commandes=Commands outputs=Output)
	 */
	protected void sequence_Definition(EObject context, Definition semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.DEFINITION__INPUTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.DEFINITION__INPUTS));
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.DEFINITION__COMMANDES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.DEFINITION__COMMANDES));
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.DEFINITION__OUTPUTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.DEFINITION__OUTPUTS));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getDefinitionAccess().getInputsInputParserRuleCall_1_0(), semanticObject.getInputs());
		feeder.accept(grammarAccess.getDefinitionAccess().getCommandesCommandsParserRuleCall_3_0(), semanticObject.getCommandes());
		feeder.accept(grammarAccess.getDefinitionAccess().getOutputsOutputParserRuleCall_6_0(), semanticObject.getOutputs());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (exprOr=ExprOr (exprAnd='and' exprAndAtt=ExprAnd)?)
	 */
	protected void sequence_ExprAnd(EObject context, ExprAnd semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (expr=Expr | (exprSim1=ExprSimple exprSim2=ExprSimple))
	 */
	protected void sequence_ExprEq(EObject context, ExprEq semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (not='not'? exprEq=ExprEq)
	 */
	protected void sequence_ExprNot(EObject context, ExprNot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (exprNot=ExprNot (exprOr='or' exprOrAtt=ExprOr)?)
	 */
	protected void sequence_ExprOr(EObject context, ExprOr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         nil='nil' | 
	 *         vari=VARIABLE | 
	 *         symb=SYMBOL | 
	 *         exprCons=Cons | 
	 *         (exprHead='hd' exprHeadAtt=Expr) | 
	 *         (exprTail='tl' exprTailAtt=Expr) | 
	 *         (nomSymb=SYMBOL symbAtt=Expr)
	 *     )
	 */
	protected void sequence_ExprSimple(EObject context, ExprSimple semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (exprSimp=ExprSimple | exprAnd=ExprAnd)
	 */
	protected void sequence_Expr(EObject context, Expr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (expGen+=Expr* expGen+=Expr)
	 */
	protected void sequence_Exprs(EObject context, Exprs semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (nom=SYMBOL definition=Definition)
	 */
	protected void sequence_Function(EObject context, Function semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.FUNCTION__NOM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.FUNCTION__NOM));
			if(transientValues.isValueTransient(semanticObject, WhileCppPackage.Literals.FUNCTION__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileCppPackage.Literals.FUNCTION__DEFINITION));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getFunctionAccess().getNomSYMBOLTerminalRuleCall_1_0(), semanticObject.getNom());
		feeder.accept(grammarAccess.getFunctionAccess().getDefinitionDefinitionParserRuleCall_3_0(), semanticObject.getDefinition());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (varIn+=VARIABLE* varIn+=VARIABLE)
	 */
	protected void sequence_Input(EObject context, Input semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (varOut+=VARIABLE* varOut+=VARIABLE)
	 */
	protected void sequence_Output(EObject context, Output semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     fonctions+=Function*
	 */
	protected void sequence_Program(EObject context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (varGen+=VARIABLE* varGen+=VARIABLE)
	 */
	protected void sequence_Vars(EObject context, Vars semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
}
