/**
 * generated by Xtext
 */
package org.xtext.example.validation;

import org.xtext.example.validation.AbstractWhileCppValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WhileCppValidator extends AbstractWhileCppValidator {
}
