/*
 * generated by Xtext
 */
package org.xtext.example.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.ui.internal.WhileCppActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WhileCppExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WhileCppActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WhileCppActivator.getInstance().getInjector(WhileCppActivator.ORG_XTEXT_EXAMPLE_WHILECPP);
	}
	
}
